<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Job Completion Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .date {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Job Completion Report</h1>
        <p>Cleaning Service Management System</p>
    </div>
    
    <div class="date">
        Generated on: {{ date('F j, Y') }}
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Service</th>
                <th>Cleaner Assigned</th>
                <th>Date Completed</th>
                <th>Rating</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($jobs as $job)
            <tr>
                <td>{{ $job->customer->name ?? 'N/A' }}</td>
                <td>{{ $job->service->name ?? 'N/A' }}</td>
                <td>
                    @if($job->employees->count() > 0)
                        {{ $job->employees->pluck('name')->implode(', ') }}
                    @else
                        Not Assigned
                    @endif
                </td>
                <td>{{ $job->completed_at ? $job->completed_at->format('M d, Y') : 'N/A' }}</td>
                <td>
                    @if($job->rating)
                        {{ number_format($job->rating->rating, 1) }}/5
                    @else
                        No rating
                    @endif
                </td>
                <td>{{ ucfirst($job->status) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center; color: #999;">No completed jobs found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Jobs: {{ $jobs->count() }}</p>
        <p>Report generated by Cleaning Service Management System</p>
    </div>
</body>
</html>
