<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer Feedback Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .date {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .rating {
            color: #f59e0b;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Feedback & Ratings Report</h1>
        <p>Cleaning Service Management System</p>
    </div>
    
    <div class="date">
        Generated on: {{ date('F j, Y') }}
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Customer</th>
                <th>Service</th>
                <th>Cleaner</th>
                <th>Rating</th>
                <th>Feedback</th>
            </tr>
        </thead>
        <tbody>
            @forelse($ratings as $rating)
            <tr>
                <td>{{ $rating->created_at->format('M d, Y') }}</td>
                <td>{{ $rating->customer->name ?? 'N/A' }}</td>
                <td>{{ $rating->job->service->name ?? 'N/A' }}</td>
                <td>{{ $rating->employee->name ?? 'N/A' }}</td>
                <td class="rating">{{ $rating->rating }}/5</td>
                <td>{{ $rating->comments ?? 'No feedback provided' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center; color: #999;">No feedback records found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Feedback Records: {{ $ratings->count() }}</p>
        <p>Report generated by Cleaning Service Management System</p>
    </div>
</body>
</html>
