<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer List Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .date {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer List Report</h1>
        <p>Cleaning Service Management System</p>
    </div>
    
    <div class="date">
        Generated on: {{ date('F j, Y') }}
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Total Jobs</th>
                <th>Last Service Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($customers as $customer)
            <tr>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->email }}</td>
                <td>{{ $customer->contact }}</td>
                <td>{{ $customer->jobs_count }}</td>
                <td>{{ $customer->jobs_max_scheduled_date ? date('Y-m-d', strtotime($customer->jobs_max_scheduled_date)) : 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Customers: {{ $customers->count() }}</p>
        <p>Report generated by Cleaning Service Management System</p>
    </div>
</body>
</html>
