<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer Retention Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .date {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Retention Report</h1>
        <p>Top Repeat Customers</p>
    </div>
    
    <div class="date">
        Generated on: {{ date('F j, Y') }}
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Customer</th>
                <th>Total Bookings</th>
                <th>First Booking</th>
                <th>Last Booking</th>
                <th>Booking Frequency</th>
            </tr>
        </thead>
        <tbody>
            @forelse($topCustomers as $customer)
            <tr>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->jobs_count }}</td>
                <td>{{ $customer->first_booking }}</td>
                <td>{{ $customer->last_booking }}</td>
                <td>
                    @if($customer->first_booking != 'N/A' && $customer->last_booking != 'N/A')
                        @php
                            $first = \Carbon\Carbon::parse($customer->first_booking);
                            $last = \Carbon\Carbon::parse($customer->last_booking);
                            $daysBetween = $first->diffInDays($last);
                            $frequency = $daysBetween > 0 ? round($customer->jobs_count / ($daysBetween/30), 1) : $customer->jobs_count;
                        @endphp
                        {{ $frequency }} jobs/month
                    @else
                        N/A
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align: center; color: #999;">No repeat customers found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ $topCustomers->count() }}</p>
        <p>Report generated by Cleaning Service Management System</p>
    </div>
</body>
</html>
